version: "3.8"

services:
  postgres:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    ports:
      - "5432:5432"

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    restart: always
    ports:
      - "4566:4566"   # Edge endpoint for all services
    environment:
      - SERVICES=ssm,s3         # Start only the services you need
      - DEFAULT_REGION=ap-south-1
      - DEBUG=1
